# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cses', '0009_auto_20161107_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('roll', models.IntegerField()),
                ('class_type', models.CharField(max_length=10)),
                ('email_id', models.EmailField(max_length=254)),
                ('year', models.DateField(default=django.utils.timezone.now, max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, max_length=200),
        ),
    ]
