# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cses', '0010_auto_20161112_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='year',
        ),
        migrations.AddField(
            model_name='student',
            name='part',
            field=models.IntegerField(default=1),
        ),
    ]
